apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: replicated/kurl
      context: "./web"
      docker:
        dockerfile: ./Dockerfile.skaffold
deploy:
  kustomize:
    path: "./kustomize/overlays/dev/"
