resources:
- api.yaml
- application-metadata.yaml
- operator.yaml
- postgres.yaml
- schemahero.yaml
- secrets.yaml
- web.yaml
configMapGenerator:
- name: kotsadm-web-scripts
  files:
  - start-kotsadm-web.sh
