apiVersion: v1
kind: Secret
metadata:
  name: kotsadm-session
stringData:
  key: "JWT" #TODO
---
apiVersion: v1
kind: Secret
metadata:
  name: kotsadm-postgres
stringData:
  uri: postgresql://kotsadm:PASSWORD_TODO@kotsadm-postgres/kotsadm?connect_timeout=10&sslmode=disable #TODO
---
apiVersion: v1
kind: Secret
metadata:
  name: kotsadm-password
stringData:
  passwordBcrypt: "TODO"
---
