apiVersion: apps/v1
kind: Deployment
metadata:
  name: kurl-proxy
  labels:
    app: kurl-proxy
spec:
  selector:
    matchLabels:
      app: kurl-proxy
  template:
    metadata:
      labels:
        app: kurl-proxy
    spec:
      containers:
      - name: proxy
        image: kurl/proxy
        env:
        - name: BIND_ADDR
          value: ":8800"
        - name: UPSTREAM_ORIGIN
          value: http://127.0.0.1:8800
        - name: TLS_SECRET_NAME
          value: kotsadm-tls
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      serviceAccount: kurl-proxy
