apiVersion: v1
kind: Service
metadata:
 name: contour
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    nodePort: $CONTOUR_HTTP_PORT
  - port: 443
    name: https
    nodePort: $CONTOUR_HTTPS_PORT
