apiVersion: velero.io/v1
kind: Backup
metadata:
  # TODO
  name: kotsadm-1
  # TODO
  namespace: velero
spec:
  includedNamespaces:
  # TODO
  - default
  # Whether or not to snapshot volumes. This only applies to PersistentVolumes for Azure, GCE, and
  # AWS. Valid values are true, false, and null/unset. If unset, Velero performs snapshots as long as
  # a persistent volume provider is configured for Velero.
  # Kurl uses restic
  snapshotVolumes: false
  # Where to store the tarball and logs.
  # TODO
  storageLocation: my-backend
  # The amount of time before this backup is eligible for garbage collection. If not specified,
  # a default value of 30 days will be used. The default can be configured on the velero server
  # by passing the flag --default-backup-ttl.
  ttl: 720h
  # Actions to perform at different times during a backup. The only hook currently supported is
  # executing a command in a container in a pod using the pod exec API. Optional.
  hooks:
    # Array of hooks that are applicable to specific resources. Optional.
    resources:
    - name: pg_dump
      includeNamespaces:
      # TODO
      - default
      includedResources:
      - pods
      labelSelector:
        matchLabels:
          app: kotsadm-api
      pre:
      - exec:
          container: backup
          command:
          - pg_dump --dbname $POSTGRES_URI > /backup/db.dump
          onError: Fail
          timeout: 300s
