apiVersion: v1
kind: ServiceAccount
metadata:
  name: kurl-web-server
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kurl-airgap-builder
  namespace: kurl
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kurl-web-server
  namespace: kurl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kurl-airgap-builder
subjects:
- kind: ServiceAccount
  name: kurl-web-server
  namespace: default
