apiVersion: v1
kind: Service
metadata:
  name: kurl
  labels:
    app: kurl
spec:
  type: NodePort
  ports:
    - name: kurl
      port: 8092
      targetPort: kurl
      nodePort: 30092
  selector:
    app: kurl