name: build-package-prod
on:
  repository_dispatch:
    types: [build-package-prod]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
        PKG: ${{ github.event.client_payload.package }}
      run: |
        git fetch --tags
        tag=$(git tag | grep '^20' | sort | tail -1)
        git checkout $tag
        export KURL_UTIL_IMAGE=replicated/kurl-util:$tag
        make dist/$PKG
        aws s3 cp dist/$PKG s3://kurl-sh/test/
