name: cron-rebuild-packages
on:
  schedule:
  - cron: '0 16 * * 6'

jobs:
  build-upload-packages:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
      run: bin/trigger-package-rebuilds.sh
