name: cron-rebuild-packages
on:
  schedule:
  - cron: '0 0 * * 7'

jobs:
  build-upload-packages:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - run: |
        git fetch --tags
        git checkout $(git tag | grep '^v20' | sort | tail -1)
        git checkout $GITHUB_REF -- bin/

    - run: |
        bin/upload-dist.sh
        aws s3 sync s3://$S3_BUCKET/staging/ s3://$S3_BUCKET/dist/
      env:
        REPLACE_PACKAGES: '1'
        DOCKER_PRUNE: '1'
        S3_BUCKET: kurl-sh
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
