name: testGrid-daily
on:
  schedule:
  - cron: "0 0 * * *"

defaults:
  run:
    working-directory: ./testgrid/tgrun

jobs:
  testgrid-init:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: setup-go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15.1

    - name: tgrun-build
      run: make build

    - name: testgrid-queue
      env:
        TESTGRID_API: "https://api.testgrid.kurl.sh/"
      
      run: |
        ./bin/tgrun queue --ref "${GITHUB_SHA:0:7}-$(date --utc +%FT%TZ)-daily"
    
